services:
  pgdb:
    build: ./pgdb
    ports:
      - '5432:5432'
    volumes:
      - pgdb_data:/bitnami/postgresql

  redis:
    build: ./redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  rabbitmq:
    build: ./rabbitmq
    ports:
      - '5672:5672'
      - '8080:15672'

  localstack:
    build: ./localstack
    ports:
      - '4566:4566'
      - '4572:4572'
    volumes:
      - localstack_data:/var/lib/localstack

volumes:
  pgdb_data:
    driver: local
  redis_data:
    driver: local
  localstack_data:
    driver: local
